import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { UseQueryResult, useQuery } from "react-query";

interface Items {
  data: {
    items: {
      id: number;
      name: string;
      shortName: string;
    }[];
  };
}
export default function Home() {
  const { isLoading, error, data }: UseQueryResult<Items> = useQuery({
    queryKey: ["allItems"],
    queryFn: () =>
      fetch("https://api.tarkov.dev/graphql", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Accept: "application/json",
        },
        body: JSON.stringify({
          query: `
          query allItems{
            items (limit: 2) {
              id
              name
              shortName
            }
          }
        `,
        }),
      }).then((res) => res.json()),
  });

  console.log(data);

  if (error) return "an error ocurred: ";

  return (
    <>
      <Head>
        <title>Tarkov app</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Tarkov <span className="text-yellow-500">T3</span> App
          </h1>
          <div className="">
            <Link
              className="flex max-w-xs flex-col rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Items</h3>
              <div className="text-lg">
                {isLoading && "loading..."}
                {data && (
                  <ul>
                    {data.data.items.map((item) => (
                      <li key={item.id}>{item.name}</li>
                    ))}
                  </ul>
                )}
              </div>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}
